apiVersion: configuration.net.nvidia.com/v1alpha1
kind: NicInterfaceNameTemplate
metadata:
  name: spectrum-x-interface-names
  namespace: nvidia-network-operator
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  pfsPerNic: 1
  rdmaDevicePrefix: "roce_r%rail_id%"
  netDevicePrefix: "eth_r%rail_id%_p%plane_id%"
  railPciAddresses:
    - ["0000:18:00.0"]
    - ["0000:1a:00.0"]
    - ["0000:3a:00.0"]
    - ["0000:4d:00.0"]
    - ["0000:5d:00.0"]
    - ["0000:9b:00.0"]
    - ["0000:ba:00.0"]
    - ["0000:ca:00.0"]
    - ["0000:cc:00.0"]
    - ["0000:db:00.0"]
